### ISSUE TITLE
2.0 - Data Sweep Lead Form Questions. To use Transformations. To put field name convention.

### ISSUE THREAD

**Issue by CesarITD** [intakedesk/PowerBI-General#526] opened 2020-04-24 14:19 UTC

**Comment by CesarITD** [comment] 2020-04-24 14:23
Work Plan:
- in 2.0 Model to change Leads Query with new strategy.
- Publish 2.0 model in Test Workspace
- To change Data Sweep version (and others???) to fix the broken fields.
- To publish new 2.0 and reports to Production.

**Comment by CesarITD** [comment] 2020-04-27 13:34
With the changes in TEST two fields was affected in file 2.0:
- Lead Form Qualifying
- Lead Type Alternative

A lot of reports will be affected with the Lead Form Fields rename, Jesus will be a Test with Phyton to do a massive fix to them.

**Comment by jesusitd** [comment] 2020-05-04 16:20
Duplicate of #533 .

Done.

**Closed as completed by jesusitd** 2020-05-04 16:20 UTC
